import { marked } from 'marked';
import { SummaryMode } from '../types';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const saveAsPDF = async (title: string, content: string, mode: SummaryMode) => {
  // 1. 임시 렌더링용 컨테이너 생성
  const container = document.createElement('div');
  container.id = 'pdf-render-container';
  container.style.position = 'fixed';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.style.width = '800px'; // A4 width proportion
  container.style.backgroundColor = 'white';
  container.style.padding = '60px';
  container.style.color = '#1f2937';
  container.style.fontFamily = "'Noto Sans KR', sans-serif";
  container.style.lineHeight = '1.7';

  // 2. 마크다운 변환
  const renderedContent = await marked.parse(content);

  // 3. 스타일 설정
  const modeStyles = (m: SummaryMode) => {
    switch (m) {
      case SummaryMode.REPORT:
        return 'border-left: 10px solid #1e40af; padding-left: 30px;';
      case SummaryMode.EMAIL:
        return 'border: 1px solid #e5e7eb; border-radius: 12px; padding: 40px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);';
      case SummaryMode.CARD:
        return 'background: linear-gradient(135deg, #4c1d95 0%, #1e1b4b 100%); color: white; padding: 80px; border-radius: 20px; text-align: center;';
      default:
        return '';
    }
  };

  container.innerHTML = `
    <div style="font-family: sans-serif; ${modeStyles(mode)}">
      <div style="border-bottom: 2px solid #4f46e5; padding-bottom: 20px; margin-bottom: 30px;">
        <h1 style="font-size: 24pt; margin: 0; color: ${mode === SummaryMode.CARD ? '#fff' : '#111'};">${title}</h1>
        <p style="font-size: 10pt; color: ${mode === SummaryMode.CARD ? 'rgba(255,255,255,0.7)' : '#6b7280'}; margin-top: 10px;">
          ClipBook AI Researcher Report | ${mode} Edition | ${new Date().toLocaleDateString()}
        </p>
      </div>
      <div class="markdown-content" style="font-size: 11pt; color: ${mode === SummaryMode.CARD ? '#fff' : '#374151'};">
        ${renderedContent}
      </div>
      <div style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 9pt; color: #9ca3af; text-align: center;">
        Generated by ClipBook AI &copy; ${new Date().getFullYear()}
      </div>
    </div>
    <style>
      .markdown-content h2 { font-size: 18pt; margin-top: 1.5em; border-bottom: 1px solid #eee; padding-bottom: 5px; color: ${mode === SummaryMode.CARD ? '#f472b6' : '#4b5563'}; }
      .markdown-content p { margin-bottom: 1em; text-align: justify; }
      .markdown-content ul, .markdown-content ol { margin-bottom: 1em; padding-left: 20px; }
      .markdown-content li { margin-bottom: 5px; }
      .markdown-content blockquote { border-left: 4px solid #4f46e5; background: #f9fafb; padding: 10px 20px; margin: 1.5em 0; font-style: italic; color: #4b5563; }
      .markdown-content strong { color: #4f46e5; }
    </style>
  `;

  document.body.appendChild(container);

  try {
    // 4. html2canvas로 캡처
    const canvas = await html2canvas(container, {
      scale: 2, // 고해상도 품질
      useCORS: true,
      logging: false,
      backgroundColor: mode === SummaryMode.CARD ? '#1e1b4b' : '#ffffff'
    });

    const imgData = canvas.toDataURL('image/png');

    // 5. jsPDF로 PDF 생성
    const pdf = new jsPDF({
      orientation: 'p',
      unit: 'mm',
      format: 'a4'
    });

    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

    // 페이지 분할 처리 (필요한 경우)
    let heightLeft = pdfHeight;
    let position = 0;
    const pageHeight = pdf.internal.pageSize.getHeight();

    pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - pdfHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
      heightLeft -= pageHeight;
    }

    // 6. 백엔드 스크립트를 통한 다운로드 처리 (폴더 선택 창 표시 및 파일명 제안 안정성 확보)
    const pdfDataUri = pdf.output('datauristring');

    // 파일명 산정: 시스템 금지 문자 제거 및 최대 길이 제한
    const safeTitle = title.replace(/[/\\?%*:|"<>]/g, '').trim().substring(0, 100) || 'ClipBook_Report';
    const fileName = `${safeTitle}.pdf`;

    chrome.runtime.sendMessage({
      action: "DOWNLOAD_FILE",
      data: {
        url: pdfDataUri,
        filename: fileName
      }
    }, (response) => {
      if (chrome.runtime.lastError || (response && !response.success)) {
        console.error('Download message failed:', chrome.runtime.lastError || response?.error);
      }
    });

  } catch (error) {
    console.error('PDF Generation Error:', error);
    throw new Error('PDF 생성 중 오류가 발생했습니다.');
  } finally {
    // 7. 임시 컨테이너 제거
    const el = document.getElementById('pdf-render-container');
    if (el) document.body.removeChild(el);
  }
};


