
export const saveAsPDF = (title: string, content: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const html = `
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: 'Noto Sans KR', sans-serif; padding: 40px; line-height: 1.6; color: #333; }
          h1 { color: #4361EE; border-bottom: 2px solid #4361EE; padding-bottom: 10px; }
          pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; }
          .footer { margin-top: 50px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 10px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="content">
          <pre>${content}</pre>
        </div>
        <div class="footer">
          Generated by ClipBook AI - ${new Date().toLocaleString()}
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.print();
};
